declare module "*.png";
declare module "*.svg";
declare module "*.jpeg";
declare module "*.jpg";
declare module "*.webp";
declare module "*.module.css";
declare module "*.css"
declare module 'dompurify';
declare module 'react-text-mask';
declare module 'react-input-mask';